sudo: required
dist: trusty
language: cpp


compiler:
  - gcc


before_install:
  - sudo add-apt-repository -y ppa:bladerf/bladerf
  - sudo add-apt-repository -y ppa:ettusresearch/uhd
  - sudo add-apt-repository -y ppa:myriadrf/drivers
  - sudo add-apt-repository -y ppa:myriadrf/gnuradio
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake qt5-default libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev gr-osmosdr gr-fcdproplus


script:
  - mkdir build
  - cd build
  - cmake -DLINUX_AUDIO_BACKEND:STRING="Pulseaudio" ..
  - make
  - cd ..
  # get appimage tools
  - wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
  - wget -c -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
  - wget -c -nv "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage"
  - chmod a+x *.AppImage
  # appimage creation
  - VERSION=`git describe --abbrev=8` && export VERSION && echo "Version = $VERSION"
  - ./linuxdeploy-x86_64.AppImage -d gqrx.desktop -e build/src/gqrx -i ./resources/icons/gqrx.svg -p qt --output appimage --appdir=./AppDir
  # check list
  - ls -lh


after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Gqrx-*.AppImage


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
