sudo: required
dist: trusty
language: cpp

compiler:
  - gcc
  - clang

env:
  - AUDIO_BACKEND="Pulseaudio"
  #- AUDIO_BACKEND="Portaudio"
  #- AUDIO_BACKEND="Gr-audio"

before_install:
  - sudo add-apt-repository -y ppa:bladerf/bladerf
  - sudo add-apt-repository -y ppa:ettusresearch/uhd
  - sudo add-apt-repository -y ppa:myriadrf/drivers
  #- sudo add-apt-repository -y ppa:myriadrf/gnuradio
  - sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-bionic
  # general update
  - sudo apt-get update -qq
  # qt5.12 updated
  - sudo apt-get install qt512-meta-full
  - source /opt/qt512/bin/qt512-env.sh 
  # gnuradio deps
  - sudo apt install git cmake g++ libboost-all-dev libgmp-dev swig python3-numpy python3-mako python3-sphinx python3-lxml doxygen libfftw3-dev libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev libqt5svg5-dev python3-pyqt5 liblog4cpp5-dev libzmq3-dev python3-yaml python3-click python3-click-plugins python3-zmq python3-scipy
  # gnuradio
  - sudo apt-get install gnuradio gnuradio-dev gr-osmosdr gr-fcdproplus soapysdr-module-all librtlsdr-dev libhackrf-dev libairspy-dev libairspyhf-dev
  # other deps
  - sudo apt-get install -y libboost-dev libpulse-dev portaudio19-dev cmake

script:
  - mkdir build
  - cd build
  - cmake -DLINUX_AUDIO_BACKEND:STRING=$AUDIO_BACKEND ..
  - make
